"""Initial migration.

Revision ID: d1e4440cdc18
Revises: 
Create Date: 2023-06-09 01:23:13.821332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1e4440cdc18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    op.drop_table('movie')
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.FLOAT(), nullable=False),
    sa.Column('timestamp', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movie',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('release_date', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('video_release_date', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('imdb_url', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('unknown', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('action', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('adventure', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('animation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('children', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('comedy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('crime', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('documentary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('drama', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fantasy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('film_noir', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('horror', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('musical', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('mystery', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('romance', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sci_fi', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('thriller', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('war', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('western', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)

    # ### end Alembic commands ###
